version: '3.7'

services:
  web:
    container_name: stockfish_api
    build: docker/app/
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8080 --reload"
    ports:
      - '3010:8080'
    volumes:
      - ./app:/app